version: '3'

services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_USER: user123
      POSTGRES_DB: haciendola
      POSTGRES_PASSWORD: password123
  app:
    image: haciendola-nest-app
    ports: 
      - 3000:3000
  